/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PvPRouteImport } from './routes/PvP'
import { Route as PvBotRouteImport } from './routes/PvBot'
import { Route as IndexRouteImport } from './routes/index'

const PvPRoute = PvPRouteImport.update({
  id: '/PvP',
  path: '/PvP',
  getParentRoute: () => rootRouteImport,
} as any)
const PvBotRoute = PvBotRouteImport.update({
  id: '/PvBot',
  path: '/PvBot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/PvBot': typeof PvBotRoute
  '/PvP': typeof PvPRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/PvBot': typeof PvBotRoute
  '/PvP': typeof PvPRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/PvBot': typeof PvBotRoute
  '/PvP': typeof PvPRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/PvBot' | '/PvP'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/PvBot' | '/PvP'
  id: '__root__' | '/' | '/PvBot' | '/PvP'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PvBotRoute: typeof PvBotRoute
  PvPRoute: typeof PvPRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/PvP': {
      id: '/PvP'
      path: '/PvP'
      fullPath: '/PvP'
      preLoaderRoute: typeof PvPRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/PvBot': {
      id: '/PvBot'
      path: '/PvBot'
      fullPath: '/PvBot'
      preLoaderRoute: typeof PvBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PvBotRoute: PvBotRoute,
  PvPRoute: PvPRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
